# Generated by Django 3.1.2 on 2020-12-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0004_address_lo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='lo',
            new_name='service_area',
        ),
        migrations.AddField(
            model_name='address',
            name='service_radius',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='شعاع فعالیت'),
        ),
    ]
