# Generated by Django 3.1.2 on 2020-12-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0005_auto_20201207_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='service_radius',
            field=models.IntegerField(null=True, verbose_name='شعاع فعالیت'),
        ),
    ]
